version: '3'
services:
  web:
    build: .
    environment:
      - POSTGRESQL_ADDON_URI=postgresql://user:password@db/test_db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
